{"uuid": "28d0dc08-0e1a-4cf7-bf77-10fdcffb92dd", "children": ["1b6159ef-7aae-463e-abec-7a5ca9aefb3b"], "befores": [{"name": "_xunit_setup_method_fixture_TestDossierUpload", "status": "broken", "statusDetails": {"message": "AttributeError: 'DossierUploadUtils' object has no attribute 'init_test_files'\n", "trace": "  File \"D:\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\python.py\", line 821, in xunit_setup_method_fixture\n    _call_with_optional_argument(func, method)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\python.py\", line 717, in _call_with_optional_argument\n    func()\n  File \"E:\\AutoTest\\FgAI\\test_001\\test_DossierUp.py\", line 47, in setup_method\n    self.zip_file_path, self.docx_file_path = self.dossier_utils.init_test_files()\n"}, "start": 1744614580183, "stop": 1744614580183}], "start": 1744614580183, "stop": 1744614580264}