INFO     automation:conftest.py:62 开始初始化Chrome WebDriver...
INFO     automation:conftest.py:75 正在安装/更新 ChromeDriver...
INFO     automation:conftest.py:78 Chrome WebDriver 创建成功
INFO     automation:conftest.py:91 操作系统: nt
INFO     automation:conftest.py:92 Python 版本: 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)]
INFO     automation:conftest.py:93 Selenium 版本: 4.30.0
WARNING  automation:conftest.py:101 检测到 Chrome 正在运行，可能会影响测试
WARNING  automation:conftest.py:108 未找到本地 ChromeDriver
INFO     automation:test_UserCenter.py:40 开始执行个人中心测试
INFO     automation:login_page.py:27 成功打开登录页面
ERROR    automation:login_page.py:36 打开登录页面失败: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=134.0.6998.118)
Stacktrace:
	GetHandleVerifier [0x0092C7F3+24435]
	(No symbol) [0x008B2074]
	(No symbol) [0x007806E3]
	(No symbol) [0x0075F83E]
	(No symbol) [0x007F455E]
	(No symbol) [0x0080EB19]
	(No symbol) [0x007ED5B6]
	(No symbol) [0x007BC54F]
	(No symbol) [0x007BD894]
	GetHandleVerifier [0x00C370A3+3213347]
	GetHandleVerifier [0x00C4B0C9+3295305]
	GetHandleVerifier [0x00C4558C+3271948]
	GetHandleVerifier [0x009C7360+658144]
	(No symbol) [0x008BB27D]
	(No symbol) [0x008B8208]
	(No symbol) [0x008B83A9]
	(No symbol) [0x008AAAC0]
	BaseThreadInitThunk [0x75005D49+25]
	RtlInitializeExceptionChain [0x7726CE3B+107]
	RtlGetAppContainerNamedObjectPath [0x7726CDC1+561]

ERROR    automation:login_page.py:85 登录过程中出现错误: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=134.0.6998.118)
Stacktrace:
	GetHandleVerifier [0x0092C7F3+24435]
	(No symbol) [0x008B2074]
	(No symbol) [0x007806E3]
	(No symbol) [0x0075F83E]
	(No symbol) [0x007F455E]
	(No symbol) [0x0080EB19]
	(No symbol) [0x007ED5B6]
	(No symbol) [0x007BC54F]
	(No symbol) [0x007BD894]
	GetHandleVerifier [0x00C370A3+3213347]
	GetHandleVerifier [0x00C4B0C9+3295305]
	GetHandleVerifier [0x00C4558C+3271948]
	GetHandleVerifier [0x009C7360+658144]
	(No symbol) [0x008BB27D]
	(No symbol) [0x008B8208]
	(No symbol) [0x008B83A9]
	(No symbol) [0x008AAAC0]
	BaseThreadInitThunk [0x75005D49+25]
	RtlInitializeExceptionChain [0x7726CE3B+107]
	RtlGetAppContainerNamedObjectPath [0x7726CDC1+561]

ERROR    automation:test_UserCenter.py:70 个人中心测试流程失败: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=134.0.6998.118)
Stacktrace:
	GetHandleVerifier [0x0092C7F3+24435]
	(No symbol) [0x008B2074]
	(No symbol) [0x007806E3]
	(No symbol) [0x0075F83E]
	(No symbol) [0x007F455E]
	(No symbol) [0x0080EB19]
	(No symbol) [0x007ED5B6]
	(No symbol) [0x007BC54F]
	(No symbol) [0x007BD894]
	GetHandleVerifier [0x00C370A3+3213347]
	GetHandleVerifier [0x00C4B0C9+3295305]
	GetHandleVerifier [0x00C4558C+3271948]
	GetHandleVerifier [0x009C7360+658144]
	(No symbol) [0x008BB27D]
	(No symbol) [0x008B8208]
	(No symbol) [0x008B83A9]
	(No symbol) [0x008AAAC0]
	BaseThreadInitThunk [0x75005D49+25]
	RtlInitializeExceptionChain [0x7726CE3B+107]
	RtlGetAppContainerNamedObjectPath [0x7726CDC1+561]
INFO     automation:test_UserCenter.py:42 个人中心测试执行完成
INFO     automation:conftest.py:118 正在关闭 WebDriver...
INFO     automation:conftest.py:120 WebDriver 已关闭
INFO     automation:conftest.py:130 正在关闭 WebDriver...
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027DA22E2EB0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/c572ddf8525045d63b5c52dba6438816
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027DA3005D00>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/c572ddf8525045d63b5c52dba6438816
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027DA3005D30>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/c572ddf8525045d63b5c52dba6438816
INFO     automation:conftest.py:132 WebDriver 已关闭