{"uuid": "cd15fb3c-e994-4b6a-b98b-d02a241522e9", "children": ["13fd05cd-878c-44cd-8563-adc3064a5bf8"], "befores": [{"name": "_xunit_setup_class_fixture_TestAssistedReading", "status": "broken", "statusDetails": {"message": "TypeError: setUp() missing 1 required positional argument: 'self'\n", "trace": "  File \"D:\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\python.py\", line 787, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, cls)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\python.py\", line 715, in _call_with_optional_argument\n    func(arg)\n  File \"E:\\AutoTest\\FgAI\\test_001\\test_assisted_read.py\", line 36, in setup_class\n    self.setUp()\n"}, "start": 1744625415766, "stop": 1744625425512}], "start": 1744625415766, "stop": 1744625425596}