{"uuid": "bb2e67ff-8c17-447d-b063-2c4e5c6ea8db", "children": ["00fcfca9-2668-4064-9435-c44ec9827397"], "befores": [{"name": "init_driver", "status": "broken", "statusDetails": {"message": "AttributeError: 'TestDossierUpload' object has no attribute 'driver'\n", "trace": "  File \"D:\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"E:\\AutoTest\\FgAI\\test_001\\test_DossierU.py\", line 56, in init_driver\n    self.driver.get_screenshot_as_png(),\n"}, "start": 1742904485282, "stop": 1742904485282}], "start": 1742904485282, "stop": 1742904485292}