{"uuid": "4df0d35d-7920-48f3-b171-2b14b3ea936d", "children": ["5c040cd8-e7f5-4def-bd92-99d168ca6c36"], "befores": [{"name": "init_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=134.0.6998.118)\nStacktrace:\n\tGetHandleVerifier [0x00007FF761B8DF85+26693]\n\t(No symbol) [0x00007FF761AEEAD0]\n\t(No symbol) [0x00007FF7619791CA]\n\t(No symbol) [0x00007FF761951763]\n\t(No symbol) [0x00007FF7619FF5EE]\n\t(No symbol) [0x00007FF761A1F975]\n\t(No symbol) [0x00007FF7619F76C3]\n\t(No symbol) [0x00007FF7619C0490]\n\t(No symbol) [0x00007FF7619C1743]\n\tGetHandleVerifier [0x00007FF761EE436D+3525677]\n\tGetHandleVerifier [0x00007FF761EF7F3B+3606523]\n\tGetHandleVerifier [0x00007FF761EECEE3+3561379]\n\tGetHandleVerifier [0x00007FF761C57C0A+853194]\n\t(No symbol) [0x00007FF761AF990F]\n\t(No symbol) [0x00007FF761AF5674]\n\t(No symbol) [0x00007FF761AF5816]\n\t(No symbol) [0x00007FF761AE4D89]\n\tBaseThreadInitThunk [0x00007FF8EA71E8D7+23]\n\tRtlUserThreadStart [0x00007FF8EC15BF6C+44]\n\n", "trace": "  File \"D:\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"E:\\AutoTest\\FgAI\\test_001\\test_DossierU.py\", line 56, in init_driver\n    self.driver.get_screenshot_as_png(),\n  File \"D:\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 1003, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n  File \"D:\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 1013, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n  File \"D:\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1742904613283, "stop": 1742904613287}], "start": 1742904613283, "stop": 1742904613347}